/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIManager;

/**
 *
 * @author naakal
 */
public class ControlSettings extends SettingsMenu {

    /**
     * Creates new form ControlSettings
     */
    public ControlSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        changeAction = new javax.swing.JButton();
        changeMoveUp = new javax.swing.JButton();
        changePause = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        aciklama = new javax.swing.JTextArea();

        setLayout(null);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        changeAction.setText("action");

        changeMoveUp.setText("move up");

        changePause.setText("pause");

        aciklama.setColumns(20);
        aciklama.setRows(5);
        aciklama.setText("açıklama yaz!!!!");
        jScrollPane1.setViewportView(aciklama);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changePause, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeMoveUp)
                    .addComponent(changeAction, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(changeMoveUp)
                        .addGap(18, 18, 18)
                        .addComponent(changeAction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changePause)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(10, 20, 270, 170);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aciklama;
    private javax.swing.JButton changeAction;
    private javax.swing.JButton changeMoveUp;
    private javax.swing.JButton changePause;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
